### ISSUE TITLE
build error on Nov. 05

### ISSUE THREAD

**Issue by mipsan** [01org/tpm2.0-tools#1]
I tested this tool yesterday well. 
However, newly cloned source tree today makes following build error

g++: error: ../tss/sysapi/libtpm.a: No such file or directory
Makefile:721: recipe for target 'tpm2_listpcrs' failed
make[1]: *** [tpm2_listpcrs] Error 1
make[1]: Leaving directory '/home/debian/tpm/tpm2.0-tools/sapi-tools'
Makefile:356: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by flihp** [comment]
Hello @mipsan. Unfortunately the build systems for the tpm2.0-tools has a dependency on the tpm2.0-tss built layout. I made a few changes to the tpm2.0-tss build the other day to build the SAPI and TCTIs as shared objects and this resulted in a few build artifacts ending up in different locations. This seems to have caused the breakage you're seeing.

IMHO the "right way" to fix this is to change the build here to link against the shared objects produced by tpm2.0-tss just like they were any other system library.

**Comment by mipsan** [comment]
Thanks @flihp , 

Hope to be cleared soon.

**Comment by gwei3** [comment]
Thanks for reporting this out. WIP.

**Comment by flihp** [comment]
hey Jimmy, I've already started in on this. Should have assigned it to myself. Sorry about that.
