### ISSUE TITLE
tpm2_rc_decode doesn't decode handle #

### ISSUE THREAD

**Issue by wcarthur1** [01org/tpm2.0-tools#100]
I entered an error code of 0x125, and it gave me the following:
warthur@ubuntu:~/dev/tpm2.0-tools/src$ ./tpm2_rc_decode 0x125
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 0 error code
  hex: 0x25
  name: TPM_RC_AUTH_MISSING
  description: command requires an authorization session for handle and it is not present.

It should also show me the handle #, 1.

**Comment by gwei3** [comment]
yes, I agree. let me label this as a enhancement.

**Comment by williamcroberts** [comment]
I'm slightly confused why the handle number would be displayed. I am reading section 6.6, and specifically looking at table 15, which shows that Bit 8 set to a 1, Bit 7 set to a 0 and Bit 6 set to 1 or 0 that, "response code defined by this specification with no handle, session, or parameter number modifier"

Your value of 0x125 in base 2 is: 100100101
Thus, bits 8-6: 100

Could you explain what you're looking for better?
