### ISSUE TITLE
General feedback on tpm2_rc_decode

### ISSUE THREAD

**Issue by wcarthur1** [01org/tpm2.0-tools#101]
Some general feedback: I think the output is way too verbose.  As a user, what I want is to see the error layer, the handle/parameter/etc. #, and the specifics of the error.  All the breakout of fields, etc. is not very interesting to me and actually makes it harder to parse to see what I'm interested in.  Just my feedback FWIW.

**Comment by gwei3** [comment]
We will create some new enhancement tickets base on this review. Thanks Will.

**Comment by williamcroberts** [comment]
Close this since there isn't a specific thing to change or fix.
