### ISSUE TITLE
Error/return/exit code cleanup for all tools

### ISSUE THREAD

**Issue by gwei3** [01org/tpm2.0-tools#117]
Currently, we are using minor number directly in all tools code to indicate errors. Need to think about more suitable way to return proper error code for different cases.

**Comment by flihp** [comment]
#137 is relevant here

**Comment by williamcroberts** [comment]
So now that everything executes from a subordinate entry point to main, I just fixed up main so only 0 and 1 can be returned to the shell for now. This may be a problem if tools need to differentiate error codes in the future, but cleans it up for now.

**Comment by williamcroberts** [comment]
Resolved in: https://github.com/01org/tpm2.0-tools/commit/06a2ffc7da2880b10c6a4f9dc7d7db7bf850b220
