### ISSUE TITLE
Establish a consistent coding style

### ISSUE THREAD

**Issue by gwei3** [01org/tpm2.0-tools#118]
Initial idea is to using Linux kernel coding style except using 4 spaces instead of tab for indent.

**Comment by williamcroberts** [comment]
Id be OK with that. However, we might want to consider a style that has a readily available easy to run formater. clang-format could be a useful tool. Especially considering that they have the --style=google built in, and Google has published comprehensive documentation here: https://github.com/google/styleguide.

Another possibility would be to create our own formating style file for clang-format or a similar tool.

**Comment by flihp** [comment]
Resolved in 05a1fed6cea183bd33b87ac348fad79cca1d2842
