### ISSUE TITLE
Need for developers wiki/guide around new infrastructure

### ISSUE THREAD

**Issue by idesai** [01org/tpm2.0-tools#131]
The new infrastructure around man pages and code structure requires some documentation to set context and ease intake of new submissions.

**Comment by flihp** [comment]
No argument here. @williamcroberts and I had a chat about putting together a "tool porting guide" but it may end up just becoming something like a "tool writers guide". I started porting one of the existing tools over just to see how bad it would get and I ran face first into #126. I'm cleaning up a patch for that now. Should have that PR ready today and the tool (tpm2_createprimary) ported soon after. I figure that should produce enough info to seed the guide.

Till then if you've got any "lessons learned" from trying to work with the options / TCTI infrastructure I made a place holder page here: https://github.com/01org/tpm2.0-tools/wiki/tool-writers-guide. Feel free to throw up whatever notes / questions you've got.

**Comment by flihp** [comment]
PR #133 is the first PR porting an existing tool over. Once we get this reviewed and merged my plan is to use it as an example for the wiki page.

**Comment by idesai** [comment]
Cool. Thanks!

**Comment by flihp** [comment]
I just finished cleaning up the wiki page with links after the merge yesterday. Did some restructuring in the last section as well. Closing this issue. Any issues with the docs should go into new issues.
