### ISSUE TITLE
use log macros for show* functions?

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#141]
When the show* functions were moved in 825c156af7c906564a3925e165d9f5d5878cfafa we discussed moving these over to use the log macros. It's not immediately clear though which macro to use. These are messages that we want printed to the console whenever the function is called. We don't want the output to be influenced by any of the logging verbosity stuff. There doesn't seem to be a LOG_* macro for this.

Thoughts @williamcroberts ?

**Comment by williamcroberts** [comment]
Yeah I thought about that after I mentioned it. The LOG macro's are likely not appropriate for showing the version number, just for error, warning and debug information. The version info should go out stdout via normal stdio routines.
