### ISSUE TITLE
Endorsement Key certificate issued by manufacturer is non standard ( non PEM/DER) format

### ISSUE THREAD

**Issue by idesai** [01org/tpm2.0-tools#142]
Endorsement Key certificate issued by the TPM manufacturer may contain metadata in addition to the certificate data, making it a non standard format.

**Comment by idesai** [comment]
PR#143 should resolve it for Intel delivered EK certificates.

**Comment by flihp** [comment]
has this been resolved? #143 was merged a while back I think.

**Comment by williamcroberts** [comment]
@idesai @flihp can we close this?
