### ISSUE TITLE
TravisCI configuration doesn't adequately cover TCTI configurations

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#178]
This is a bit of a weird situation but due to dependencies on the socket TCTI library there are a number of things that prevent us from enabling the `common` module when it is disabled. So the current strategy is to only compile `common.c` into `libutil` when the socket TCTI is enabled. In the process of porting commands over to use the new common option / TCTI module the most error prone step is refactoring any code / dependencies that may exist between the tool and the `common` module [as described here](https://github.com/01org/tpm2.0-tools/wiki/tool-porting-guide#common-module-refactoring).

This issue is compounded by the default `./configure` behavior is to have the socket TCTI enabled by default. This causes bugs in the build to be missed under the default build behavior.

AFAIK the right way to address this is to add a few additional build runs in the `.travis.yml` that builds the tools with a few permutations of the TCTI support:
1. `./configure` which enables both TCTIs
1. `./configure --without-tcti-socket`
1. `./configure --without-tcti-device`

That effectively triples the build time but it will save us time in debugging our work to port over the tools.

**Comment by gwei3** [comment]
Let me do this quickly.

**Comment by gwei3** [comment]
Fix merged already, so close it.
