### ISSUE TITLE
Enhance tpm2_takeownership to reconfigure lockout related properties

### ISSUE THREAD

**Issue by gwei3** [01org/tpm2.0-tools#185]
Since tpm2_takeownership -c was changed to use lockout auth to clear tpm ownership, it is very easy to trigger the disabled status of lockout auth if using wrong lockout auth to clear tpm. The default value for TPM_PT_LOCKOUT_RECOVERY might be very large or just 0(require reset), so it would be easier to give use choices to reconfigure it as needed.

Meanwhile, other properties like TPM_PT_MAX_AUTH_FAIL, TPM_PT_LOCKOUT_INTERVAL should be able to be easily reconfigured per needs by users.

**Comment by idesai** [comment]
@gwei3 this has been factored into the tpm2_dictionarylockout tool. Can close this one? Thanks!

**Comment by gwei3** [comment]
yes, let's close it since tpm2_dictionarylockout tool already supported the required functions.
