### ISSUE TITLE
intelEKcert2PemDer.sh modifies input file

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#186]
The sed command on line 35 in this tool uses `-i` which modifies the file in place: https://github.com/01org/tpm2.0-tools/blob/master/scripts/utils/intelEKcert2PemDer.sh#L35

I think that most users would be surprised to have this tool not only generate the DER file that they expect, but to also modified the input file. This will make running the tool against the same input file more than once impossible. IMHO the "right way" to fix this is to combine the commands on line 35 and 36 into a single pipeline. Something like:
```
sed -i 's/-/+/g;s/_/\//g;s/%3D/=/g;s/^{.*certificate":"//g;s/"}$//g;' $1 | base64 --decode > $certBasename.cer
```
may work.

**Comment by williamcroberts** [comment]
Yeah I don't think folks would like this.
