### ISSUE TITLE
Tools Enhancements for OpenXT Integration

### ISSUE THREAD

**Issue by crogers1** [01org/tpm2.0-tools#191]
Hey!  I'm from the [OpenXT](https://github.com/openxt) project and am currently working on integrating TPM 2.0 into our platform using the Intel projects (TSS and these tools).  We use the TPM for certain tasks that the current tpm2.0-tools doesn't fully support yet.  To that end,  I'd like to use this issue as a tracker for some contributions I would like to make to the tpm2.0-tools project with respect to the following features, should the community and maintainers be interested in accepting them:
- sealing 
- unsealing
- pcr extension
- detecting tpm ownership
- building authorization policies (with PCR state)

I can have a PR ready for a pcr extension tool relatively quickly; my other code changes might take a bit longer to clean up and be ready for review.

Chris

**Comment by idesai** [comment]
Welcome Chris @crogers1 
For sealing and unsealing you can try the tpm2_create and tpm2_unseal tools.
For tpm ownership there is tpm2_takeownership. Is that what you meant by detecting ownership?
Inorder to ease the PR process, there is also a tool porting guide @https://github.com/01org/tpm2.0-tools/wiki/tool-porting-guide.
Thanks.

**Comment by crogers1** [comment]
Thanks for the link to the guide.  By "detecting ownership" I meant using Tss2_Sys_Get_Capability, with TPM_PT_PERMANENT to check which bits are set for owner/endorsement/lockout auth. Useful for checking if takeownership has been called since the last tpm clear.

I've successfully sealed and unsealed data, the tpm2_create and tpm2_unseal work fine.  My use-case for sealing/unsealing is a bit more complicated.

**Comment by idesai** [comment]
Ah. I see. @flihp has this added to the tpm2_dump_capability tool and that should give information about the ownership.

**Comment by flihp** [comment]
Howdy @crogers1. A bit of data to add to the comment from @idesai above:

Using the `tpm2_dump_capability` tool to detect "ownership" in a script might look something like this:
```
if tpm2_dump_capability --capability=properties-variable | grep -q 'ownerAuthSet:[[:space:]]\+set'; then echo "Owner Auth Set"; fi
```

**Comment by crogers1** [comment]
@flihp @idesai, thanks, I'll use the new dump_capability tool from now on.

**Comment by williamcroberts** [comment]
@crogers1 Is there anything else remaining on this ticket or can we close it?

**Comment by crogers1** [comment]
@williamcroberts It's good to close, I'll take care of it.  Thanks for all the help!
