### ISSUE TITLE
Signing attestation key using endorsement key.

### ISSUE THREAD

**Issue by Iyer-VivekAnand** [01org/tpm2.0-tools#194]
I am trying to certify my Attestation Key with Endorsement Key. When I run tpm2_certify to certify AK with EK, I get error 
"TPM2_Certify failed. Error Code: 0x12f". I also found that EK cannot be used to sign other objects.

I am trying to find a way to attest AK with EK. Basically, I am looking for a way to prove that the AK originated from the same TPM where the EK is generated. Is there an standard way in TPM itself or any workaround for my requirement?

**Comment by idesai** [comment]
Greetings. 
Typically EK isn't directly used for signing as it defeats the privacy objectives and so typically the tpm manufacturers also do not certify ek for direct signing like this and so EK are typically decryption only keys. That being said AIK generated from the EK can be used for signing. The association of AIK with the EK you would have to proven with  credential activation. The tool tpm2_activatecredential should do just that.

**Comment by Iyer-VivekAnand** [comment]
Thanks @idesai for the solution.

**Comment by kiranpradeep** [comment]
@idesai This query is unrelated to this issue: I am using trousers stack on Ubuntu Linux. I am trying to prove device identity based on endorsement key(EK_pub) white listing on server. Currently to prove identity I am needing to create AIK followed by creating linkage between EK and AIK. Device anonymity is not important for me and so I like to make direct use of EK_pub and EK_priv. In the above reply, you have mentioned EK is used as decryption only key. Is it possible for me to use EK_priv to decrypt data encrypted with EK_pub. I am able to extract EK_certificate (EK_pub) and encrypt data using the same. But I am not able to find a way to decrypt with EK_priv as you have mentioned above.

**Comment by b4stien** [comment]
> [@idesai](https://github.com/idesai) [...] Device anonymity is not important for me and so I like to make direct use of EK_pub and EK_priv. In the above reply, you have mentioned EK is used as decryption only key. Is it possible for me to use EK_priv to decrypt data encrypted with EK_pub. I am able to extract EK_certificate (EK_pub) and encrypt data using the same. But I am not able to find a way to decrypt with EK_priv as you have mentioned above.

I have been stuck there too, did you ever unstuck @kiranpradeep? I'd wager it's a common usecase to auth servers in a datacenter but I can't find any easy material, does someone have a reference?

_I realize this is an old issue, sorry for reviving it._

**Comment by JuergenReppSIT** [comment]
The decryption of data encrypted with EK_pub is not possible because the EK is a restricted key.
Perhaps this tutorial is interesting for you:
https://tpm2-software.github.io/2020/06/12/Remote-Attestation-With-tpm2-tools.html

**Comment by b4stien** [comment]
Thanks for the pointer!

For future reader and if I correctly grasped [this other tutorial](https://github.com/tpm2dev/tpm.dev.tutorials/blob/master/Attestation/ek-secret.md#concept), `TPM2_ActivateCredential()` is able to decrypt data encrypted with EK_pub (encrypted via `TPM2_MakeCredential()`).

**Comment by JuergenReppSIT** [comment]
@b4stien Also thanks for the pointer. That's true. Data with the size of the digest can be decrypted with the EK.
Here how to do it with the tpm tools where the name of a TPM key, instead of the temporary key in the tutorial,  is used for TPM2_MakeCredential.
```
echo "12345678" > secret
tpm2_createek -c ek.ctx  -G ecc
tpm2_readpublic -c ek.ctx -o ek.pem -f pem -n ek.name
tpm2_createak -C ek.ctx -c ak.ctx -G ecc -g sha256 -s ecdsa -u ak.pub -n ak.name
file_size=`ls -l ak.name | awk {'print $5'}`
loaded_key_name=`cat ak.name | xxd -p -c $file_size`
tpm2 makecredential -T none -Q -u ek.pem -s secret -n $loaded_key_name -o credential -G ecc

tpm2_startauthsession --policy-session -S session
tpm2_policysecret -S session -c 0x4000000B ""
tpm2_activatecredential -c ak.ctx -C ek.ctx -i credential  -o secret-decrypted  -P session:session
```
