### ISSUE TITLE
after TBoot, tpm2.0-tools does not work

### ISSUE THREAD

**Issue by mipsan** [01org/tpm2.0-tools#2]
to setup measured boot, TBoot is employed to my host.
TBoot: https://sourceforge.net/projects/tboot/

However, after booting with TBoot, TPM utilities do not work at all.

Any idea about it?

Thanks 
youngwha

1. resource manager
Accept socket: 0x7
Resource Manager Other CMD Server accepted client
Accept socket: 0x6
Resource Manager TPM CMD Server accepted client
|| Loaded transient object handles:
|| 0x80000000, || Loaded transient object handles:
|| 0x80000000, || Loaded transient object handles:
|| 0x80000000, || Loaded transient object handles:
|| 0x80000000, || Loaded transient object handles:
|| 0x80000000, OtherCmdServer died (Other CMD), socket: 0x7.
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x6.

2. sapi-tools
Show all PCR banks:

Bank/Algorithm: TPM_ALG_SHA1(0x0004)
This bank can not be read, tpm error 0xc010c

Bank/Algorithm: TPM_ALG_SHA256(0x000b)
This bank can not be read, tpm error 0xc010c

Bank/Algorithm: TPM_ALG_SHA384(0x000c)
This bank can not be read, tpm error 0xc010c

Bank/Algorithm: TPM_ALG_SHA512(0x000d)
This bank can not be read, tpm error 0xc010c

Bank/Algorithm: TPM_ALG_SM3_256(0x0012)
This bank can not be read, tpm error 0xc010c

**Comment by flihp** [comment]
Doing some house keeping here: From reading through the TPM2.0-TSS issue tracker it looks like this was an issue with the resource manager. See https://github.com/01org/TPM2.0-TSS/issues/83

Looks like this was resolved a month ago so I'm closing this issue. If this issue should remain open for any reason please re-open it and add some data explaining the situation.
