### ISSUE TITLE
sample.h is a sample of nightmare

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2.0-tools#203]
sample.h has unused methods and statically coded sysContext initialization, when the common infrastructure milestone is complete, this serves as a reminder that you wanted to break out all the code cleanly.

**Comment by flihp** [comment]
looks like this was lifted directly from the TPM2.0-TSS "sample" code: https://github.com/01org/TPM2.0-TSS/blob/master/test/common/sample/sample.h. Not really the sort of code we want to encourage people to use as reference unfortunately. The small bits of cleanup I've already done here has been much what I imagine cleaning up an oil spill would be like ... :disappointed:
