### ISSUE TITLE
tpm2_create does not enforce or use the policy option

### ISSUE THREAD

**Issue by idesai** [01org/tpm2.0-tools#206]
tpm2_create does not enforce/ use the policy from the file stated in the options during the object creation.

**Comment by martinezjavier** [comment]
Wasn't this fixed by commit 5992cb777baa ("Adding option to enforce policy based authorization for the object created")?

@idesai Is anything else missing to close this issue?

**Comment by idesai** [comment]
@martinezjavier correct, this could be closed.
