### ISSUE TITLE
check for warnings from 'man' command in CI

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#211]
In #208 we got a patch to fix bad comment prefixes that were uncovered by a Debian packaging tool. From the information provided in the PR the tool executes man with the following options which causes warnings to be output on stderr:
```
man --warnings -E UTF-8 -l -Tutf8 -Z ./man/man8/tpm2_akparse.8
```

To make life easier for packagers we should run this as part of our CI setup and cause a failure if our man pages produce errors or warnings.

**Comment by williamcroberts** [comment]
Any particular reason we cannot use: man --warnings -lZ ./man/man8/tpm2_akparse.8, do we need -E and -T?

**Comment by williamcroberts** [comment]
I tested a hacked on tpm2_akparse manpage that had an error:

$ man --warnings -lZ ./man/man8/tpm2_akparse.8 1>/dev/null
<standard input>:33: warning: macro `foo' not defined

That looks pretty good for output, and its silent on no warnings/errors

**Comment by williamcroberts** [comment]
Not fixing.
