### ISSUE TITLE
load_external of a private key

### ISSUE THREAD

**Issue by danglus** [01org/tpm2.0-tools#250]
Hi,
  Given the key duplication seems so complex, I'm working on a script that will simply load an OpenSSL private key to the TPM using the tpm2_loadexternal command.
(so far I only did the reverse direction, and only for the public-key, of course).

Has anyone tried loading a private key (in the clear) to the TPM?

  Thanks,
Dan

**Comment by williamcroberts** [comment]
@danglus not that I know of, but I am new to this project. @idesai, @gwei3  or @flihp might have more historical information in it.

Awesome you're working on a script, please post a PR when you're done!

**Comment by idesai** [comment]
@danglus loadexternal can only load public keys. load command can load both, but only for tpm generated keys.
What you need is a utility for import. @williamcroberts may be we can merge or link this with issue #218

**Comment by williamcroberts** [comment]
I don't think we can merge it, but Ill close this one and link #218 with this one

**Comment by idesai** [comment]
@williamcroberts Thanks!

**Comment by williamcroberts** [comment]
Automagically crosslinked via reference of #218, thanks github

**Comment by danglus** [comment]
HI,

   Can’t I just build a “TPM2B_SENSITIVE        *inPrivate” structure with the private key in the clear and load it to the TPM?

Reading  the “12.3 TPM2_LoadExternal” from part 3 (commands), I got the impression that this is possible.



Thanks,
Dan

**Comment by tomaszpr** [comment]
Hi,
Can **tpm2_import** tool be used to import private RSA keys to TPM chip ?
Thanks,
Tom

**Comment by williamcroberts** [comment]
@tomaszpr In theory I think that's yes. But currently the tool only supports symmetric keys AFAIK.

**Comment by SilverJan** [comment]
I assume that the latest master version resolves this issue? I saw that the method `tpm2_import` has been added.

**Comment by williamcroberts** [comment]
@SilverJan yes it does. tpm2_import can now be used to load AES128/256 and RSA1024/2048 and 4096 (untested) keys.
