### ISSUE TITLE
test_tpm2_encryptdecrypt test should probe Symmetric Encryption support using GetCapability

### ISSUE THREAD

**Issue by tonyespy** [01org/tpm2.0-tools#254]
If the test_tpm2_encryptdecrypt.sh test is run on a device with a TPM 2.0 implementation that doesn't support Symmetric Encryption, the test will fail.

It should be possible for the script to use the new tpm2_dump_capability (in master) command to request the attributes for the TPM2_EncryptDecrypt command (CC=0x164).  If no results are returned, the command isn't supported by the device, and the test shouldn't fail.

This is being reported as of tpm2.0-tools version 1.1.0.

**Comment by flihp** [comment]
Good catch. Seems like the right thing to do here would be to have tpm2_encryptdecrypt.c check for command support before execution. Probably something we should do for each tool but I guess that all depends on what commands are required vs optional.
