### ISSUE TITLE
test_tpm2_unseal shouldn't use the platform hierarchy as a default

### ISSUE THREAD

**Issue by tonyespy** [01org/tpm2.0-tools#255]
test_tpm2_unseal uses the platform hierarchy by default, which means it will always fail on a device which doesn't have an enabled or provisioned platform hierarchy, which is the case on most devices which don't fully support Trusted Boot.

For Ubuntu Core 16, we're in the process of changing this test to use the endorsement hierarchy by default, as this means the test runs and succeeds on most platforms.

Reported against tpm2.0-tools version 1.1.0.

**Comment by flihp** [comment]
I dunno much about the unseal tool or the associated test, but you can determine whether the platform hierarchy is enabled by querying the TPMA_STARTUP_CLEAR attribute structure. I think this is in the TPM_CAP_TPM_PROPERTIES capability group tagged with TPM_PT_STARTUP_CLEAR. This should be something that can be queried using the tpm2_dump_capability tool.

Either way making the hierarchy used for this tool (or any?) configurable / selectable would be an improvement.
