### ISSUE TITLE
fix format specifiers in tpm2_send_command

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#258]
In the read_command_from_file and write_response_to_file I borked up a few of the LOG_* statements. These were dumping information about the size of some object but I used the wrong length specifier: `l` where `z` was appropriate. This works on 64 bit systems but not 32bit systems where size_t is not a long int.

**Comment by williamcroberts** [comment]
fixed: 0b744d1b13ce57b4be547ae773d7db1cbccf9a04
