### ISSUE TITLE
wrong time in 2.0.0-beta_0 CHANGELOG 

### ISSUE THREAD

**Issue by yunyings** [01org/tpm2.0-tools#277]
In 2.0.0-beta_0 CHANGELOG:
v2.0 - 2016-04-03
* Tracked on the milestone: https://github.com/01org/tpm2.0-tools/milestone/2
* Reworked all the tools to support configurable TCTIs, based on build time
  configuration, one can specify the tcti via the --tcti (-T) option to all
  tools.
* tpm2_getrandom interface made -s a positional argument.
* Numerous bug fixes.

201"6" must be a typo. Should be 2017, isn't it?

**Comment by williamcroberts** [comment]
Fixed: https://github.com/01org/tpm2.0-tools/commit/b6b60da5be1329f7597bc6b20c658c683ec720d3
