### ISSUE TITLE
test_tpm2_activecredential.sh result is fail

### ISSUE THREAD

**Issue by GaryC920** [01org/tpm2.0-tools#280]
I tried to run test_all.sh script on my system but I got fail on test_tpm2_activecredential.sh item. Is there any problem on my system?
[http://i455.photobucket.com/albums/qq272/shrekc/tpm2.jpg](url)

**Comment by williamcroberts** [comment]
404 on the link. Make sure you run test_all.sh very carefully, and follow how it is run in the .travis.yml file.

**Comment by GaryC920** [comment]
update the link.
<a href="http://s455.photobucket.com/user/shrekc/media/tpm2.jpg.html" target="_blank"><img src="http://i455.photobucket.com/albums/qq272/shrekc/tpm2.jpg" border="0" alt=" photo tpm2.jpg"/></a>

**Comment by williamcroberts** [comment]
Hmm, that doesn't provide a lot of information, What are your system details? Are you running against a real tpm or the simulator? Is that the only test that fails?

**Comment by GaryC920** [comment]
I run the test_all.sh script on our Purley DP MB with real TPM module (Infineon SLB 9670 chip) and there are 3 fail items (test_tpm2_activecredential.sh, test_tpm2_quote.sh and test_tpm2_encryptdecrypt.sh).
For test_tpm2_quote.sh and test_tpm2_encryptdecrypt.sh items, Infineon guy said that Infineon TPM didn't support it so it's expected results.
For test_tpm2_activecredential.sh item, he had no idea why it fail on our system.
Is there any further information I can provided to you for debug?

**Comment by williamcroberts** [comment]
If you can pinpoint which API call in the tool is failing, and it's error code, that would help. The error code can be passed to tpm2_rc_decode to get some details out of it.

**Comment by GaryC920** [comment]
May I know how can I get the error code for tpm2_rc_decode to decode?
<a href="http://s455.photobucket.com/user/shrekc/media/Snap1.jpg.html" target="_blank"><img src="http://i455.photobucket.com/albums/qq272/shrekc/Snap1.jpg" border="0" alt=" photo Snap1.jpg"/></a>

**Comment by williamcroberts** [comment]
You'll need to hack on the code/run it in a debugger and find out where it's failing, unfortunately the error messages are not super helpful here.

**Comment by williamcroberts** [comment]
Closing, please submit an issue if #282 did not fix the issue for you.
