### ISSUE TITLE
tpm2_send_command add input and output files

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2.0-tools#308]
Add input and output file options for tpm2_send_command

**Comment by martinezjavier** [comment]
This issues has been fixed by commit 161d66100933 ("tpm2_send_command: add input and output options"), but the "Fixes: 308" tag in the commit message missed a number sign and so Github didn't close it automatically.

**Comment by martinezjavier** [comment]
@williamcroberts not sure if you noticed my previous comment? It's safe to close this issue now.

**Comment by williamcroberts** [comment]
Yep, done.
