### ISSUE TITLE
tpm2_getmanufec not gracefully failing when a --ECcertFile option isn't used

### ISSUE THREAD

**Issue by martinezjavier** [01org/tpm2.0-tools#361]
The tpm2_getmanufec expects to always be called with a  -E, --ECcertFile option, if that's not the case then it fails with the following error:

$ tpm2_getmanufec -g 0x01 -O -N -U -f test_ek.pub -S https://ekop.intel.com/ekcertservice/
...
ERROR: Could not open file for writing: "(null)"

**Comment by williamcroberts** [comment]
Fixed in https://github.com/01org/tpm2.0-tools/commit/bb856ded2c85093891c7f1f4608cd5f448f0b3d9
