### ISSUE TITLE
Not resolved error codes by rc-decode

### ISSUE THREAD

**Issue by tkcsndrs** [01org/tpm2.0-tools#368]
Hello Support Team,

I have 4 NV entries stored in the TPM.
3 of them are locked after they've been successfully written. They are supposed to be used as symmetric keys for AES-CBC later. The fourth one (not key) can be written any time for the application logic.  
The following problems occur sporadically. 
Application calls Tss2_Sys_GetCapability and afterwards Tss2_Sys_NV_ReadPublic in every 100 ms.
Unfortunately, Tss2_Sys_GetCapability returns 0x17A error code and Tss2_Sys_NV_ReadPublic returns with 0x169, sporadically. None of them can be resolved by re-decode.

- Is there any timing constraints for these 2 functions or in general for nv ram access functions?
- Can you help us to decode the 2 errors, why they suppose to mean?

Thank you for the support!
Best regards,
Andras Takacs

**Comment by webmeister** [comment]
Your error codes look suspiciously like command codes, not real error codes. 0x17a is TPM_CC_GetCapability and 0x169 is TPM_CC_NV_ReadPublic. Are you sure those are reported as error codes? Then maybe something gets mixed up during communication and it would be interesting to see the corresponding data streams that are exchanged with the TPM.

**Comment by tkcsndrs** [comment]
Hello Webmeister!

Yes, I am sure, they are reported as return codes of the Tss2_Sys_GetCapability() and Tss2_Sys_NV_ReadPublic. I think you might be right, communication gets mixed up. 
What should I do to be able to observe these exchanged data? 
What should be activated? 

Thanks!

**Comment by idesai** [comment]
@tkcsndrs I think @webmeister is pointing out correctly. Either the current/ previous tpm operation is taking too long or has rendered the tpm to a halt.
Are you able to run something like get random when this happens?

**Comment by tkcsndrs** [comment]
Hi, 
get random operates well and Tss2_Sys_GetCapability, Tss2_Sys_NV_ReadPublic  at next call after 100ms.
I try to get the exchanged data.

**Comment by williamcroberts** [comment]
@tkcsndrs Is this reproduce able with the tools code and can you output there output, or are you using the system api raw?

For the system API, the github is here: https://github.com/01org/TPM2.0-TSS
For general help (like this bug, as no bug is being reported), please use the mailing list:
https://lists.01.org/mailman/listinfo/tpm2

**Comment by williamcroberts** [comment]
If you need firther help, hit the mailing list. https://lists.01.org/mailman/listinfo/tpm2
