### ISSUE TITLE
Only TPM_ALG_KEYEDHASH can be used when passing data for object creation

### ISSUE THREAD

**Issue by martinezjavier** [01org/tpm2.0-tools#369]
If an object is created with data to be sealed, tpm2_create fails with all algorithms type but -G 0x8 (TPM_ALG_KEYEDHASH). For example, with -G 0x23 (TPM_ALG_ECC):

```
$ tpm2_create -g 0xb -G 0x23 -o obj.pub -O obj.priv -c primary.context -L policy.digest -E -I- <<< "foobar"
nameAlg = 0x000b
type = 0x0023
contextParentFile = primary.context
inSensitive.t.sensitive.data.t.size = 7
ObjectAttribute: 0x00060032

Create Object Failed ! ErrorCode: 0x1c2

$ tpm2_rc_decode 0x1c2
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x02
  identifier: TPM_RC_ATTRIBUTES
  description: inconsistent attributes
parameter
  hex: 0x100
  identifier:  TPM_RC_1
  description:  (null)
```

The object attribute is **0x60032**, which means that the following TPMA_OBJECT bits has been set:

* fixedTPM
* fixedParent
* sensitiveDataOrigin
* decrypt
* sign / encrypt

At the very lesat, sensitiveDataOrigin shouldn't be set since we are providing sensitive data with the -I option, not sure what decrypt and sign should be in this case...

But with -g 0x8 (TPM_ALG_KEYEDHASH):

```
$ tpm2_create -g 0xb -G 0x8 -o obj.pub -O obj.priv -c primary.context -L policy.digest -E -I- <<< "foobar"
nameAlg = 0x000b
type = 0x0008
contextParentFile = primary.context
inSensitive.t.sensitive.data.t.size = 7
ObjectAttribute: 0x00000012

Create Object Succeed !
```

In this case the object attribute is **0x12** which is:

* fixedTPM
* fixedParent

I see in [setAlg() function in tpm2_create.c](https://github.com/01org/tpm2.0-tools/blob/master/tools/tpm2_create.c#L61) that only for the TPM_ALG_KEYEDHASH case the I_flag is taken into account. For all others algorithms, inPublic->t.publicArea.objectAttributes.sensitiveDataOrigin = 1

I tried to obvious and that was to force the same object attributes when using TPM_ALG_ECC, but still complains about inconsistent attributes:

```
$ tpm2_create -g 0xb -G 0x23 -A 0x12 -o obj.pub -O obj.priv -c primary.context -L policy.digest -E -I- <<< "foobar"
nameAlg = 0x000b
type = 0x0023
contextParentFile = primary.context
inSensitive.t.sensitive.data.t.size = 7
ObjectAttribute: 0x00000012

Create Object Failed ! ErrorCode: 0x2c2
```

This time the error code is slightly different though:

```
 $ tpm2_rc_decode 0x2c2
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x02
  identifier: TPM_RC_ATTRIBUTES
  description: inconsistent attributes
parameter
  hex: 0x200
  identifier:  TPM_RC_2
  description:  (null)
```

**Comment by martinezjavier** [comment]
Ok, I just found in the **Trusted Platform Module Library Part 2: Structures Family “2.0” Level 00 Revision 01.38 September 29, 2016** that tpm2_create is doing the right thing according to the specification:

**8.3.3.5 Bit[5] – sensitiveDataOrigin**

Creation If inSensitive.sensitive.data.size is zero, then this attribute shall be SET in the template;
otherwise, it shall be CLEAR in the template.

NOTE 2 The inSensitive.sensitive.data.size parameter is required to be zero for an asymmetric key so sensitiveDataOrigin is required to be SET.

NOTE 3 The inSensitive.sensitive.data.size parameter may not be zero for a data object so sensitiveDataOrigin is required to be CLEAR. A data object has type = TPM_ALG_KEYEDHASH and its sign and decrypt attributes are CLEAR.

Does this mean that for sealing data, only TPM_ALG_KEYEDHASH can be used?

Should tpm2_create check if (I_flag && type != TPM_ALG_KEYEDHASH) and return and error / call showArgMismatch() in that case?

Or maybe even not require a -G option when passing -I and just setting type to TPM_ALG_KEYEDHASH in that case.

**Comment by idesai** [comment]
@martinezjavier i think that input validation would be great to arrest any issues early. 👍

**Comment by martinezjavier** [comment]
@idesai Ok, I'll add the sanity check. Thanks!

**Comment by williamcroberts** [comment]
@idesai @martinezjavier, I have always hated the raw hex format for algorithms, ill have a PR up soon to use nice names for those too.

**Comment by idesai** [comment]
@williamcroberts that'd be great, nice_names concept should extend to object attributes that go into set_alg in the tools as well.

**Comment by williamcroberts** [comment]
@idesai - agreed, folks shouldn't have to memorize the specification down to raw-hex for anything, but raw-input should always be accepted.
