### ISSUE TITLE
how to use tpm2_evictcontrol

### ISSUE THREAD

**Issue by EthanPark2017** [01org/tpm2.0-tools#378]
I made a storage primary key and a child key according to "How to use tpm2 tools".
Then, tried to make them persistent using tpm2_evictcontrol, but failed.

pi@raspberrypi:~$ tpm2_createprimary -A o -K objectpass -g 0x000b -G 0x0001 -C po.ctx
nameAlg = 0x000b
type = 0x0001
contextFile = po.ctx

CreatePrimary Succeed ! Handle: 0x800000ff

pi@raspberrypi:~$ tpm2_create -c po.ctx -P objectpass -K subobjectpass -g 0x000b -G 0x0001 -o key.pub -O key.priv
contextParentFile = po.ctx
nameAlg = 0x000b
type = 0x0001
ObjectAttribute: 0x00060072

Create Object Succeed !
pi@raspberrypi:~$ tpm2_load -c po.ctx -P objectpass -u key.pub -r key.priv -n key.name -C obj.ctx
contextParentFile = po.ctx
contextFile = obj.ctx

Load succ.
LoadedHandle: 0x80000100

pi@raspberrypi:~$ tpm2_evictcontrol -A o -H 0x800000ff -S 0x810000ff -P objectpass
persistentHandle: 0x810000ff
ERROR: EvictControl failed, error code: 0x284

pi@raspberrypi:~$ tpm2_evictcontrol -A o -H 0x80000100 -S 0x81000100 -P subobjectpass
persistentHandle: 0x81000100
ERROR: EvictControl failed, error code: 0x284

Can anyone tell me what's wrong in my test and how to use tpm2_evictcontol?

**Comment by martinezjavier** [comment]
@EthanPark2017 you use the tpm2_rc_decode tool to get more info about the error code, e.g:

```
$ tpm2_rc_decode 0x284
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x04
  identifier: TPM_RC_VALUE
  description: value is out of range or is not correct for the context
handle
  hex:0x200
  identifier:  TPM_RC_2
  description:  (null)
```

AFAICT the problem is that you not passing the correct loaded object handle.

In your example, the loaded object handle is 0x80000100, so instead your command should be:

```
$ tpm2_evictcontrol -A o -H 0x80000100 -S 0x810000ff -P objectpass
```
Alternatively, you could pass the loaded object context instead of the handle, since you are using the -C option in your tpm2_load command. So this should work for you as well:

```
$ tpm2_evictcontrol -A o -C obj.ctx -S 0x810000ff -P objectpass
```

**Comment by williamcroberts** [comment]
This should be done on the mailing list, not in the issue tracker: https://lists.01.org/mailman/listinfo/tpm2
