### ISSUE TITLE
implicit-fallthrough error when compiling for Fedora rawhide

### ISSUE THREAD

**Issue by yunyings** [01org/tpm2.0-tools#382]
I'm trying to update tpm2-tools package to 2.1.0 release for Fedora rawhide and EPEL7. 

Got such error when doing "fedpkg build" (build log - https://kojipkgs.fedoraproject.org//work/tasks/2931/20832931/build.log):
tools/main.c: In function 'main':
tools/main.c:62:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         fprintf (stderr,
         ^~~~~~~~~~~~~~~~
                  "failed to load manpage, check your environment / PATH\n");
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

tools/tpm2_dump_capability.c: In function 'dump_tpm_capability':
tools/tpm2_dump_capability.c:596:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         dump_command_attr_array (capabilities->command.commandAttributes,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  capabilities->command.count);
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by yunyings** [comment]
Googled and here is a post with same issue, cause and fix also included:
https://github.com/ponylang/ponyc/issues/1581

**Comment by yunyings** [comment]
Just saw the pull request from Philip is exactly for this issue:
https://github.com/01org/tpm2.0-tools/pull/381

Will close this issue.

**Comment by liuqun** [comment]
The break/fallthough warning of tpm2-tools was fixed by the following commit:

https://github.com/01org/tpm2-tools/pull/542/commits/0847fda64d8395b6ecca889e49bc5216e95c580c
