### ISSUE TITLE
Detect presence of openssl headers & library @ config time

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#44]
See #42. This will obsolete bedcc03e1321b31fd729eae838899d22b69ab122
The only reason we still have to explicitly mention the tcti library is because it's broken. I'm working on that upstream currently.

**Comment by gwei3** [comment]
I think  bedcc03 already fixed both #42 and #44. What is missing from your view?

**Comment by flihp** [comment]
My mistake @gwei3. I didn't get bedcc03 before making these tickets. It's exactly what I was wanting :smile:
