### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by dguerri** [01org/tpm2.0-tools#51]
Hi,
thanks for writing and maintaining these tools.
It would be great if you could improve the manual providing some "real-file" example involving multiple TPM2 commands and external tools? 
For instance, I was thinking about signing something with the TPM and verifying it with OpenSSL or encrypt something using OpenSSL and using the TPM to decrypt it.

Thanks!

**Comment by gwei3** [comment]
Good suggestion for documentation enhancement. thanks.

**Comment by dguerri** [comment]
I have written a short article about using tpm2-tools to sign a message and verify the signature w/ openssl: https://dguerriblog.wordpress.com/2016/03/03/tpm2-0-and-openssl-on-linux-2/
I have just used shell commands, but it would be easy to write an application (C, Python or whatever) that converts TPM2 data to PEM/DER!

**Comment by gwei3** [comment]
Thanks for the sharing. It is really a good try and good suggestion for creating new tools to convert data between tpm2 format and PEM/DER. I will:
1. reference your article in the wiki for a example of how to utilize tpm2.0-tools
2. create a new issue to track the request for new tools.

**Comment by idesai** [comment]
Thanks Davide for the excellent post. Thanks Wei creating the placeholder. PR#135 is intended as a start to put the new tools in place.

**Comment by williamcroberts** [comment]
https://github.com/01org/tpm2.0-tools/pull/138
