### ISSUE TITLE
tpm2_getmanufec URL

### ISSUE THREAD

**Issue by jethrogb** [01org/tpm2.0-tools#55]
What is the URL for use with tpm2_getmanufec for an Intel TPM?

**Comment by jethrogb** [comment]
The correct URL is listed here https://technet.microsoft.com/itpro/windows/keep-secure/protect-high-value-assets-by-controlling-the-health-of-windows-10-based-devices 

https://ekop.intel.com/ekcertservice/

**Comment by gwei3** [comment]
thanks for the update.
