### ISSUE TITLE
TPM Tools from IBM

### ISSUE THREAD

**Issue by atomsoftwarestudios** [01org/tpm2.0-tools#57]
Hi,

As I was planning to add some additional tools in order to be possible to use i.e. policy authentization I have read almost full TCG spec and I discovered that current version of tools allow just the user authentication mode.

It would require a lot of work to implement features I needed for my project so I was looking for some solution and I have found this:

https://sourceforge.net/projects/ibmtpm20tss/

It is almost complete implementation of the TCG spec. Althoug it is not ideal (as it does not support ie. threading) it allow to use policy authentication and many other features.

Take look on it.

Regards,
Franta

**Comment by mikzaq** [comment]
How can I make this work with a hardware TPM?

**Comment by atomsoftwarestudios** [comment]
It should be the same as for software. Which one do you mean? TPM2.0 tools or IBM implementation?

**Comment by mikzaq** [comment]
The IBM implementation. I seem to have been able to make it work by changing the TPM CMD port of the TPM2 TSS resourcemgr however

**Comment by atomsoftwarestudios** [comment]
It is well documented. As far as I remember it is possible to change some environment variable to use soft / hard TPM but I have changed it directly somewhere else (i think makefile) and compiled for hardware tpm instead of software simulator. It is mentioned in the readme.

**Comment by mikzaq** [comment]
Oh! I think I see it in the readme now

To change the default TPM interface to the TPM device driver:
With a makefile:
-DTPM_INTERFACE_TYPE_DEFAULT="\"dev\""
With an environment variable:
> setev TPM_INTERFACE_TYPE     dev

Thanks for your help!

**Comment by atomsoftwarestudios** [comment]
Exactly ;) You're welcome. But the env variable didn't work for me so I have used the other way and recompiled the code.

**Comment by flihp** [comment]
Closing this issue since it's not related to this project. Please use the IBM forum / mailing list etc for discussion related to the IBM project.
