### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by mikzaq** [01org/tpm2.0-tools#71]
Is there any way to decipher the error codes that get thrown by the commands? I am tryng to use tpm2_nvdefine and am getting a 0x14b error, but I have no idea what this means.

**Comment by flihp** [comment]
This sounds like a feature request to me. Setting the label.

**Comment by flihp** [comment]
Assigning to myself. I'm half way through a tool for this.

**Comment by gwei3** [comment]
This was fixed by the recently merged PR #82.
