### ISSUE TITLE
Trusted boot

### ISSUE THREAD

**Issue by mikzaq** [01org/tpm2.0-tools#72]
Is there any way I can use the currently implemented tools to seal a key to the pcr state? From looking at the tools, it seems as though "tpm2_create" seals data, but how can I base this on the state of the pcrs?

**Comment by gwei3** [comment]
I think this is a duplicate of #80. Just as you tried, you need to make a tool to create an authPolicy and store it into a file, then parse that file as the input policyfile to tpm2_create.
