### ISSUE TITLE
cpp files but not using cpp features

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#8]
I guess this is a question for @gwei3 directly. Just wondering why all of the sources are in .cpp files, compiled with g++ but AFAIK we don't actually use any C++ features (no STL, no classes etc). I'm sure there's a reason but since this is my first pass over the code it's not readily apparent.

Apologies in advance for the n00b question :)

**Comment by gwei3** [comment]
This is a good question. :-)

At the beginning of this project, we think for apps C++ should be a better choice, but according to the project developers' experience, most code are still written in C style. But we can see some exception in tpm2_akparse.cpp: SaveKeyToFile() which was defined as a template which is a C++ feature. Nevertheless, if necessary, we can turn this project to a pure C project.

**Comment by wcarthur1** [comment]
I had some trouble getting some of the sockets code on Windows to build unless some of the files were .cpp files.  Don’t know if this could be worked around, but I messed with it for a while before giving up and going the .cpp route.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Good info. Thanks. If any work comes of this it should be in separate tickets so I'll close this issue. Question answered.
