### ISSUE TITLE
tpm2_create issue

### ISSUE THREAD

**Issue by mikzaq** [01org/tpm2.0-tools#81]
Using tpm2_create returns "incorrect port number", but none of the other commands seem to have this problem. I have checked the .cpp file and it appears that all is as it should be. Also, using the -port argument to specify the resourcemgr port has no effect.

**Comment by gwei3** [comment]
this is strange, let me look at it.

**Comment by gwei3** [comment]
not able to reproduce based on the latest code. Can you give some logs?

**Comment by mikzaq** [comment]
I am dumb. I was using -port instead of --port.
