### ISSUE TITLE
Make tools configurable for TCTI interface selection

### ISSUE THREAD

**Issue by gwei3** [01org/tpm2.0-tools#87]
So far, tools can only use resourcemgr TCTI implementation. It would be a good direction to enhance it to be able to use other existing TCTI implementation such as device TCTI, simulator TCTI, etc, and also make it configurable. Further, it will even better to make the TCTI choices extensible without code change.

**Comment by flihp** [comment]
Enabling TCTIs at configure time would be my preference here. autoconf supports options to the configure script like --with-tcti-device / --with-tcti-socket. This would give optimum flexibility at the expense of some complexity in the build.

**Comment by flihp** [comment]
This is addressed in PR #113. Not applied to all tools yet but provides framework & a few new tools to model transition for remaining tools.

**Comment by flihp** [comment]
Closing after merge of #113. Still need to port tools over though. Should have a new ticket.
