### ISSUE TITLE
stdafx.h and other windows stuff

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#90]
Many of the source files have windows specific stuff in them (see https://github.com/01org/tpm2.0-tools/blob/master/src/tpm2_activatecredential.cpp#L43) but we don't have any windows build files and AFAIK the tools have never supported windows. So this code may or may not work. I'd recommend that we remove these windowsisms. If we need to support alternative platforms in the future we can figure out what special stuff we need to do to accommodate those build environments as part of a new effort.

**Comment by gwei3** [comment]
I agree.
