### ISSUE TITLE
Using tpm2_getpubek to get ECC EK key

### ISSUE THREAD

**Issue by wlee888** [01org/tpm2.0-tools#98]
I am using Intel NUC5i3MYHE and it is has the Infineon's SLB9665xx2.0 chip which contains 2 EK credentials, one for RSA public key and the other for ECC public key.   I have no problems calling  tpm2_getpubek to get  RSA  EK public key  but  I can't use the same command line to get the ECC EK public key for some reason.  The following is what I ran:

1) Attempt to get ECC EK pub key
./tpm2_getpubek -H 0x81010000 -g 0x0023 -f ecc1.pub
Accept socket:  0x8
Resource Manager Other CMD Server accepted client 
Accept socket:  0x9
Resource Manager TPM CMD Server accepted client

......TPM2_CreatePrimary Error. TPM Error:0x2ca......
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x9.
OtherCmdServer died (Other CMD), socket: 0x8.

Checking what the error code means:
./tpm2_rc_decode 0x2ca
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x0a
  identifier: TPM_RC_TYPE
  description: the type of the value is not appropriate for the use
parameter
  hex: 0x200
  identifier:  TPM_RC_2
  description:  (null)

But this works for RSA:

 ./tpm2_getpubek -H 0x81010000 -g 0x001 -f ek3.pub
Accept socket:  0x6
Resource Manager Other CMD Server accepted client
Accept socket:  0x7
Resource Manager TPM CMD Server accepted client

EK create succ.. Handle: 0x80000000
EvictControl EK persistent succ.
Flush transient EK succ.
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x7.
OtherCmdServer died (Other CMD), socket: 0x6.

Does anyone know what I might be doing wrong or what I am missing?  I would like to get the endorsement key for ECC.  Thanks so much for your help!

**Comment by gwei3** [comment]
This should have been fixed already. Try to pull the latest code and try again.

**Comment by WilliamMartinIII** [comment]
I get that same error code 0x2CA using a modified tpmtest.cpp from the Intel TPM 2.0 TSS Version 1.0 with a new createPrimary test function added inside tpmtest.cpp  as follows: 


void TestCreatePrimaryECC()
{
    UINT32 rval;
    TPM2B_SENSITIVE_CREATE  inSensitive;
    TPM2B_PUBLIC            inPublic;
    TPM2B_DATA              outsideInfo;
    TPML_PCR_SELECTION      creationPCR;
    TPMS_AUTH_COMMAND sessionData;
    TPMS_AUTH_RESPONSE sessionDataOut;
    TSS2_SYS_CMD_AUTHS sessionsData;
   const char *msg;
   const char *submsg;
   const char *num;


    TSS2_SYS_RSP_AUTHS sessionsDataOut;
    TPM2B_NAME name;
    TPM2B_PUBLIC outPublic;
    TPM2B_CREATION_DATA creationData;
    TPM2B_DIGEST creationHash;
    TPMT_TK_CREATION creationTicket;

    TPMS_AUTH_COMMAND *sessionDataArray[1];
    TPMS_AUTH_RESPONSE *sessionDataOutArray[1];

    sessionDataArray[0] = &sessionData;
    sessionDataOutArray[0] = &sessionDataOut;

    sessionsDataOut.rspAuths = &sessionDataOutArray[0];
    sessionsData.cmdAuths = &sessionDataArray[0];

    sessionsDataOut.rspAuthsCount = 1;

    inSensitive.t.sensitive.userAuth = loadedSha1KeyAuth;
    inSensitive.t.sensitive.userAuth = loadedSha1KeyAuth;
    inSensitive.t.sensitive.data.t.size = 0;
    inSensitive.t.size = loadedSha1KeyAuth.b.size + 2;
    inPublic.t.publicArea.type = TPM_ALG_ECDAA;
    inPublic.t.publicArea.nameAlg = TPM_ALG_SHA256;

    // First clear attributes bit field.
    *(UINT32 *)&( inPublic.t.publicArea.objectAttributes) = 0;
    inPublic.t.publicArea.objectAttributes.restricted = 0;
    inPublic.t.publicArea.objectAttributes.userWithAuth = 1;
    inPublic.t.publicArea.objectAttributes.sign = 1;
    inPublic.t.publicArea.objectAttributes.fixedTPM = 1;
    inPublic.t.publicArea.objectAttributes.fixedParent = 1;
    inPublic.t.publicArea.objectAttributes.sensitiveDataOrigin = 1;

    inPublic.t.publicArea.authPolicy.t.size = 0;

    inPublic.t.publicArea.parameters.eccDetail.symmetric.algorithm = TPM_ALG_NULL;
    inPublic.t.publicArea.parameters.eccDetail.scheme.scheme = TPM_ALG_ECDAA;
    inPublic.t.publicArea.parameters.eccDetail.scheme.details.ecdaa.hashAlg = TPM_ALG_SHA256;
    inPublic.t.publicArea.parameters.eccDetail.scheme.details.ecdaa.count = 1;
    inPublic.t.publicArea.parameters.eccDetail.curveID = TPM_ECC_BN_P256;
    inPublic.t.publicArea.parameters.eccDetail.kdf.scheme = TPM_ALG_NULL;

    outsideInfo.t.size = 0;
    creationPCR.count = 0;

    sessionData.sessionHandle = TPM_RS_PW;

    // Init nonce.
    sessionData.nonce.t.size = 0;

    // init hmac
    sessionData.hmac.t.size = 0;

    // Init session attributes
    *( (UINT8 *)((void *)&sessionData.sessionAttributes ) ) = 0;
    sessionsData.cmdAuthsCount = 1;
    sessionsData.cmdAuths[0] = &sessionData;


    outPublic.t.size = 0;
    creationData.t.size = 0;
    printf("Before call to Tss2_Sys_CreatePrimary\n");
// fails TPM_RH_PLATFORM, TPM_RH_OWNER - fails TPM_RH_ENDORSEMENT -- Fails TPM_RH_NULL
// but spec says it should be endorsement hierarchy...
    rval = Tss2_Sys_CreatePrimary( sysContext, TPM_RH_ENDORSEMENT, &sessionsData, &inSensitive, &inPublic,

            &outsideInfo, &creationPCR, &handle2048rsa, &outPublic, &creationData, &creationHash,
            &creationTicket, &name, &sessionsDataOut );
        printf("\nerrorcode: 0x%x\n", rval);
        if (rval != 0) printf("\nerror level is %d\n", TSS2_ERROR_LEVEL(rval));

    CheckPassed( rval );
}

- so if you put a call in for TestCreatePrimaryECC() in place of TestCreatePrimary() you will  see the output 
Before call to Tss2_Sys_CreatePrimary

errorcode: 0x2ca

error level is 46792704
           passing case:    FAILED:    TPM Error: 0x2ca

I ran this against the ibm SW tpm 532 and also the 832.

thanks

Bill
